import type { Metadata } from "next";
import {Manrope, Work_Sans} from "next/font/google";
import "./globals.css";
import SiteFooter from "@/components/sections/global/site-footer";
import SiteHeader from "@/components/sections/global/site-header";

const manrope = Manrope({
  variable: "--font-manrope",
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${workSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <SiteHeader/>
      <div className={'flex-grow flex flex-col items-center *:flex-grow *:w-full'}>
        {children}
      </div>
      <SiteFooter/>
      </body>
    </html>
  );
}
